# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Hugo\Desktop\L\CG\OpenGL\OpenCV_Tuto_with_GL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Hugo\Desktop\L\CG\OpenGL\OpenCV_Tuto_with_GL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\msys64\mingw64\bin\ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\msys64\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\msys64\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Hugo\Desktop\L\CG\OpenGL\OpenCV_Tuto_with_GL\CMakeFiles C:\Users\Hugo\Desktop\L\CG\OpenGL\OpenCV_Tuto_with_GL\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Hugo\Desktop\L\CG\OpenGL\OpenCV_Tuto_with_GL\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps\glfw-build\CMakeFiles\uninstall.dir\build.make _deps/glfw-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps\glfw-build\src\CMakeFiles\update_mappings.dir\build.make _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps\glfw-build\src\CMakeFiles\glfw.dir\build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

include/glad/src/glad.obj: include/glad/src/glad.c.obj
.PHONY : include/glad/src/glad.obj

# target to build an object file
include/glad/src/glad.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/glad/src/glad.c.obj
.PHONY : include/glad/src/glad.c.obj

include/glad/src/glad.i: include/glad/src/glad.c.i
.PHONY : include/glad/src/glad.i

# target to preprocess a source file
include/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/glad/src/glad.c.i
.PHONY : include/glad/src/glad.c.i

include/glad/src/glad.s: include/glad/src/glad.c.s
.PHONY : include/glad/src/glad.s

# target to generate assembly for a file
include/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/glad/src/glad.c.s
.PHONY : include/glad/src/glad.c.s

include/imgui/imgui.obj: include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.obj

# target to build an object file
include/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.cpp.obj

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_draw.obj: include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.obj

# target to build an object file
include/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.cpp.obj

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_impl_glfw_gl3.obj: include/imgui/imgui_impl_glfw_gl3.cpp.obj
.PHONY : include/imgui/imgui_impl_glfw_gl3.obj

# target to build an object file
include/imgui/imgui_impl_glfw_gl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_impl_glfw_gl3.cpp.obj
.PHONY : include/imgui/imgui_impl_glfw_gl3.cpp.obj

include/imgui/imgui_impl_glfw_gl3.i: include/imgui/imgui_impl_glfw_gl3.cpp.i
.PHONY : include/imgui/imgui_impl_glfw_gl3.i

# target to preprocess a source file
include/imgui/imgui_impl_glfw_gl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_impl_glfw_gl3.cpp.i
.PHONY : include/imgui/imgui_impl_glfw_gl3.cpp.i

include/imgui/imgui_impl_glfw_gl3.s: include/imgui/imgui_impl_glfw_gl3.cpp.s
.PHONY : include/imgui/imgui_impl_glfw_gl3.s

# target to generate assembly for a file
include/imgui/imgui_impl_glfw_gl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/imgui/imgui_impl_glfw_gl3.cpp.s
.PHONY : include/imgui/imgui_impl_glfw_gl3.cpp.s

include/stb_image/stb_image.obj: include/stb_image/stb_image.cpp.obj
.PHONY : include/stb_image/stb_image.obj

# target to build an object file
include/stb_image/stb_image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/stb_image/stb_image.cpp.obj
.PHONY : include/stb_image/stb_image.cpp.obj

include/stb_image/stb_image.i: include/stb_image/stb_image.cpp.i
.PHONY : include/stb_image/stb_image.i

# target to preprocess a source file
include/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/stb_image/stb_image.cpp.i
.PHONY : include/stb_image/stb_image.cpp.i

include/stb_image/stb_image.s: include/stb_image/stb_image.cpp.s
.PHONY : include/stb_image/stb_image.s

# target to generate assembly for a file
include/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/include/stb_image/stb_image.cpp.s
.PHONY : include/stb_image/stb_image.cpp.s

src/cv_image.obj: src/cv_image.cpp.obj
.PHONY : src/cv_image.obj

# target to build an object file
src/cv_image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/cv_image.cpp.obj
.PHONY : src/cv_image.cpp.obj

src/cv_image.i: src/cv_image.cpp.i
.PHONY : src/cv_image.i

# target to preprocess a source file
src/cv_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/cv_image.cpp.i
.PHONY : src/cv_image.cpp.i

src/cv_image.s: src/cv_image.cpp.s
.PHONY : src/cv_image.s

# target to generate assembly for a file
src/cv_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/cv_image.cpp.s
.PHONY : src/cv_image.cpp.s

src/index_buffer.obj: src/index_buffer.cpp.obj
.PHONY : src/index_buffer.obj

# target to build an object file
src/index_buffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/index_buffer.cpp.obj
.PHONY : src/index_buffer.cpp.obj

src/index_buffer.i: src/index_buffer.cpp.i
.PHONY : src/index_buffer.i

# target to preprocess a source file
src/index_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/index_buffer.cpp.i
.PHONY : src/index_buffer.cpp.i

src/index_buffer.s: src/index_buffer.cpp.s
.PHONY : src/index_buffer.s

# target to generate assembly for a file
src/index_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/index_buffer.cpp.s
.PHONY : src/index_buffer.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderer.obj: src/renderer.cpp.obj
.PHONY : src/renderer.obj

# target to build an object file
src/renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/renderer.cpp.obj
.PHONY : src/renderer.cpp.obj

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/shader.obj: src/shader.cpp.obj
.PHONY : src/shader.obj

# target to build an object file
src/shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/shader.cpp.obj
.PHONY : src/shader.cpp.obj

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/tests/test.obj: src/tests/test.cpp.obj
.PHONY : src/tests/test.obj

# target to build an object file
src/tests/test.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test.cpp.obj
.PHONY : src/tests/test.cpp.obj

src/tests/test.i: src/tests/test.cpp.i
.PHONY : src/tests/test.i

# target to preprocess a source file
src/tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test.cpp.i
.PHONY : src/tests/test.cpp.i

src/tests/test.s: src/tests/test.cpp.s
.PHONY : src/tests/test.s

# target to generate assembly for a file
src/tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test.cpp.s
.PHONY : src/tests/test.cpp.s

src/tests/test_clear_color.obj: src/tests/test_clear_color.cpp.obj
.PHONY : src/tests/test_clear_color.obj

# target to build an object file
src/tests/test_clear_color.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_clear_color.cpp.obj
.PHONY : src/tests/test_clear_color.cpp.obj

src/tests/test_clear_color.i: src/tests/test_clear_color.cpp.i
.PHONY : src/tests/test_clear_color.i

# target to preprocess a source file
src/tests/test_clear_color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_clear_color.cpp.i
.PHONY : src/tests/test_clear_color.cpp.i

src/tests/test_clear_color.s: src/tests/test_clear_color.cpp.s
.PHONY : src/tests/test_clear_color.s

# target to generate assembly for a file
src/tests/test_clear_color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_clear_color.cpp.s
.PHONY : src/tests/test_clear_color.cpp.s

src/tests/test_texture_2D.obj: src/tests/test_texture_2D.cpp.obj
.PHONY : src/tests/test_texture_2D.obj

# target to build an object file
src/tests/test_texture_2D.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_texture_2D.cpp.obj
.PHONY : src/tests/test_texture_2D.cpp.obj

src/tests/test_texture_2D.i: src/tests/test_texture_2D.cpp.i
.PHONY : src/tests/test_texture_2D.i

# target to preprocess a source file
src/tests/test_texture_2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_texture_2D.cpp.i
.PHONY : src/tests/test_texture_2D.cpp.i

src/tests/test_texture_2D.s: src/tests/test_texture_2D.cpp.s
.PHONY : src/tests/test_texture_2D.s

# target to generate assembly for a file
src/tests/test_texture_2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/tests/test_texture_2D.cpp.s
.PHONY : src/tests/test_texture_2D.cpp.s

src/texture.obj: src/texture.cpp.obj
.PHONY : src/texture.obj

# target to build an object file
src/texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/texture.cpp.obj
.PHONY : src/texture.cpp.obj

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/vertex_array.obj: src/vertex_array.cpp.obj
.PHONY : src/vertex_array.obj

# target to build an object file
src/vertex_array.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_array.cpp.obj
.PHONY : src/vertex_array.cpp.obj

src/vertex_array.i: src/vertex_array.cpp.i
.PHONY : src/vertex_array.i

# target to preprocess a source file
src/vertex_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_array.cpp.i
.PHONY : src/vertex_array.cpp.i

src/vertex_array.s: src/vertex_array.cpp.s
.PHONY : src/vertex_array.s

# target to generate assembly for a file
src/vertex_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_array.cpp.s
.PHONY : src/vertex_array.cpp.s

src/vertex_buffer.obj: src/vertex_buffer.cpp.obj
.PHONY : src/vertex_buffer.obj

# target to build an object file
src/vertex_buffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_buffer.cpp.obj
.PHONY : src/vertex_buffer.cpp.obj

src/vertex_buffer.i: src/vertex_buffer.cpp.i
.PHONY : src/vertex_buffer.i

# target to preprocess a source file
src/vertex_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_buffer.cpp.i
.PHONY : src/vertex_buffer.cpp.i

src/vertex_buffer.s: src/vertex_buffer.cpp.s
.PHONY : src/vertex_buffer.s

# target to generate assembly for a file
src/vertex_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/vertex_buffer.cpp.s
.PHONY : src/vertex_buffer.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... update_mappings
	@echo ... glfw
	@echo ... main
	@echo ... include/glad/src/glad.obj
	@echo ... include/glad/src/glad.i
	@echo ... include/glad/src/glad.s
	@echo ... include/imgui/imgui.obj
	@echo ... include/imgui/imgui.i
	@echo ... include/imgui/imgui.s
	@echo ... include/imgui/imgui_draw.obj
	@echo ... include/imgui/imgui_draw.i
	@echo ... include/imgui/imgui_draw.s
	@echo ... include/imgui/imgui_impl_glfw_gl3.obj
	@echo ... include/imgui/imgui_impl_glfw_gl3.i
	@echo ... include/imgui/imgui_impl_glfw_gl3.s
	@echo ... include/stb_image/stb_image.obj
	@echo ... include/stb_image/stb_image.i
	@echo ... include/stb_image/stb_image.s
	@echo ... src/cv_image.obj
	@echo ... src/cv_image.i
	@echo ... src/cv_image.s
	@echo ... src/index_buffer.obj
	@echo ... src/index_buffer.i
	@echo ... src/index_buffer.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/renderer.obj
	@echo ... src/renderer.i
	@echo ... src/renderer.s
	@echo ... src/shader.obj
	@echo ... src/shader.i
	@echo ... src/shader.s
	@echo ... src/tests/test.obj
	@echo ... src/tests/test.i
	@echo ... src/tests/test.s
	@echo ... src/tests/test_clear_color.obj
	@echo ... src/tests/test_clear_color.i
	@echo ... src/tests/test_clear_color.s
	@echo ... src/tests/test_texture_2D.obj
	@echo ... src/tests/test_texture_2D.i
	@echo ... src/tests/test_texture_2D.s
	@echo ... src/texture.obj
	@echo ... src/texture.i
	@echo ... src/texture.s
	@echo ... src/vertex_array.obj
	@echo ... src/vertex_array.i
	@echo ... src/vertex_array.s
	@echo ... src/vertex_buffer.obj
	@echo ... src/vertex_buffer.i
	@echo ... src/vertex_buffer.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

